# Generated by Django 4.1.3 on 2022-11-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_member_rank_alter_tag_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='answer_dislikes', to='app.member'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='answer_likes', to='app.member'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='question_dislikes', to='app.member'),
        ),
        migrations.AlterField(
            model_name='question',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='question_likes', to='app.member'),
        ),
    ]
