# Generated by Django 4.1.3 on 2022-11-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_answer_date_alter_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='AskME/static/img/unknown.jpg', upload_to=''),
        ),
    ]
