# Generated by Django 4.1.3 on 2022-11-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_answer_dislike_users_alter_answer_like_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, related_name='answer_dislikes', to='app.member'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='answer_likes', to='app.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, default='AskME/static/img/unknown.jpg', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, related_name='question_dislikes', to='app.member'),
        ),
        migrations.AlterField(
            model_name='question',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='question_likes', to='app.member'),
        ),
    ]
